### ISSUE TITLE
Sentences are merged after conversion

### ISSUE THREAD

**Issue by jdixosnd** [joeyism/jsonl-to-conll#1]
After converting to conll2003 all the sentences(lines) are merged and there is no separator between them,
To fix this issue, I have added `f.writelines("\n")` (will be line 8)  in `jsonl-to-conll/jsonl_to_conll/io.py` oustide of for loop `for line in each_json`

**Comment by joeyism** [comment]
submit a PR and i'll take a look

**Comment by joeyism** [comment]
Thanks, published in [1.0.2](https://github.com/joeyism/jsonl-to-conll/releases/tag/1.0.2)
